version: '3'
services:
  nosql-db:
    image: mongo
    ports:
      - '27017:27017'
    container_name: nosql-db
    volumes:
      - ./db/:/data/db

  # rabbitMQ:
  #   image: rabbitmq:3-management
  #   ports:
  #     - '15672:15672'
  #     - '5672:5672'
  #   container_name: message-broker

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - '8002:8002'
    restart: always
    links:
      - nosql-db
    volumes:
      - .:/app
      - /app/products/node_modules

  customers:
    build:
      dockerfile: Dockerfile
      context: ./customers
    container_name: customers
    ports:
      - '8001:8001'
    restart: always
    links:
      - nosql-db
    volumes:
      - .:/app
      - /app/customers/node_modules

  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - '8003:8003'
    restart: always 
    links:
      - nosql-db
    volumes:
      - .:/app
      - /app/shopping/node_modules

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    links:
      - products
      - customers
      - shopping
    ports:
      - '80:80'
